services:
  db:
    image: postgres:10.0-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  api:
    image: ghcr.io/mostlydevops/wordsmith-api-stable:latest

  web:
    image: ghcr.io/mostlydevops/wordsmith-web-stable:latest
    ports:
     - "8080:80"